In [1]:
#traing model for 64 channels
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ==================================================
# Load features
# ==================================================

X_train = np.load(
    "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power/S001/S001_train_bandpower_X.npy"
)

y_train = np.load(
    "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power/S001/S001_train_bandpower_y.npy"
)

X_test = np.load(
    "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power/S001/S001_test_bandpower_X.npy"
)

y_test = np.load(
    "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power/S001/S001_test_bandpower_y.npy"
)

# ==================================================
# LDA Pipeline
# ==================================================

model = Pipeline([
    ("scaler", StandardScaler()),
    ("lda", LinearDiscriminantAnalysis())
])

# ==================================================
# Train
# ==================================================

model.fit(X_train, y_train)

# ==================================================
# Predict
# ==================================================

y_pred = model.predict(X_test)

# ==================================================
# Metrics
# ==================================================

acc = accuracy_score(y_test, y_pred)

print(f"Accuracy: {acc:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy: 0.6000

Confusion Matrix
[[13  0  2]
 [ 4  2  1]
 [ 5  0  3]]

Classification Report
              precision    recall  f1-score   support

           1       0.59      0.87      0.70        15
           2       1.00      0.29      0.44         7
           3       0.50      0.38      0.43         8

    accuracy                           0.60        30
   macro avg       0.70      0.51      0.53        30
weighted avg       0.66      0.60      0.57        30



In [ ]:
#for 3 channels 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
)

# ==================================================
# Paths
# ==================================================
FEATURE_DIR = "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power_c3_cz_c4/S001"

# ==================================================
# Load features
# ==================================================
X_train = np.load(f"{FEATURE_DIR}/S001_train_bandpower_X.npy")
y_train = np.load(f"{FEATURE_DIR}/S001_train_bandpower_y.npy")
X_test = np.load(f"{FEATURE_DIR}/S001_test_bandpower_X.npy")
y_test = np.load(f"{FEATURE_DIR}/S001_test_bandpower_y.npy")

event_id_map = np.load(f"{FEATURE_DIR}/S001_event_id_map.npy", allow_pickle=True).item()
channel_order = np.load(f"{FEATURE_DIR}/S001_channel_order.npy")

print("Event ID mapping (name -> code):", event_id_map)
print("Channel order:", list(channel_order))
print("Feature vector shape:", X_train.shape, "-> 2 features (mu, beta) per channel\n")

# ==================================================
# LDA Pipeline
# ==================================================
model = Pipeline([
    ("scaler", StandardScaler()),
    ("lda", LinearDiscriminantAnalysis())
])

# ==================================================
# Train
# ==================================================
model.fit(X_train, y_train)

# ==================================================
# Predict
# ==================================================
y_pred = model.predict(X_test)

# ==================================================
# Metrics
# ==================================================
acc = accuracy_score(y_test, y_pred)

# Map integer codes back to names for a readable confusion matrix / report
code_to_name = {v: k for k, v in event_id_map.items()}
labels_sorted = sorted(event_id_map.values())
label_names = [code_to_name[c] for c in labels_sorted]

print(f"Accuracy: {acc:.4f}\n")
print("Confusion Matrix (rows=true, cols=predicted)")
print("Labels order:", label_names)
print(confusion_matrix(y_test, y_pred, labels=labels_sorted))
print("\nClassification Report")
print(classification_report(y_test, y_pred, labels=labels_sorted, target_names=label_names))

In [ ]:
#traing the model for 15 channels
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
)

# ==================================================
# Paths
# ==================================================
FEATURE_DIR = "/Users/prajwalnara/Documents/EEG-motor-imagery/data/features/band_power_15/S001"

# ==================================================
# Load features
# ==================================================
X_train = np.load(f"{FEATURE_DIR}/S001_train_bandpower_X.npy")
y_train = np.load(f"{FEATURE_DIR}/S001_train_bandpower_y.npy")
X_test = np.load(f"{FEATURE_DIR}/S001_test_bandpower_X.npy")
y_test = np.load(f"{FEATURE_DIR}/S001_test_bandpower_y.npy")

event_id_map = np.load(f"{FEATURE_DIR}/S001_event_id_map.npy", allow_pickle=True).item()
channel_order = np.load(f"{FEATURE_DIR}/S001_channel_order.npy")

print("Event ID mapping (name -> code):", event_id_map)
print("Channel order:", list(channel_order))
print("Feature vector shape:", X_train.shape, "-> 2 features (mu, beta) per channel\n")

# ==================================================
# LDA Pipeline
# ==================================================
model = Pipeline([
    ("scaler", StandardScaler()),
    ("lda", LinearDiscriminantAnalysis())
])

# ==================================================
# Train
# ==================================================
model.fit(X_train, y_train)

# ==================================================
# Predict
# ==================================================
y_pred = model.predict(X_test)

# ==================================================
# Metrics
# ==================================================
acc = accuracy_score(y_test, y_pred)

# Map integer codes back to names for a readable confusion matrix / report
code_to_name = {v: k for k, v in event_id_map.items()}
labels_sorted = sorted(event_id_map.values())
label_names = [code_to_name[c] for c in labels_sorted]

print(f"Accuracy: {acc:.4f}\n")
print("Confusion Matrix (rows=true, cols=predicted)")
print("Labels order:", label_names)
print(confusion_matrix(y_test, y_pred, labels=labels_sorted))
print("\nClassification Report")
print(classification_report(y_test, y_pred, labels=labels_sorted, target_names=label_names))